services:
  - type: web
    name: keta-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        value: 8925039039:AAEcfp5WbaRCrZqkDdI8vF7Qp2AW1enVQd8
      - key: WEBHOOK_URL
        value: https://keta-bot-79vw.onrender.com
      - key: MONGO_URI
        value: mongodb+srv://oyedeleoreofe_db_user:396Sk6752aybClMi@cluster0.guhg0wv.mongodb.net/?appName=Cluster0
      - key: ADMIN_GROUP_ID
        value: -1003867460811
      - key: ADMIN_IDS  
        value: 1686970676,8925039039,6148056554,7495523053
      - key: BANK_NAME
        value: MoniePoint
      - key: ACCOUNT_NAME
        value: Oreofeoluwa Joseph Oyedele
      - key: ACCOUNT_NUMBER
        value: 9065189953
      - key: NODE_ENV
        value: production
      - key: BASE_SEPOLIA_RPC_URL
        value: https://base-sepolia.g.alchemy.com/v2/L6GkcIxENz-4j7Yj89Jmk
      - key: ETH_SEPOLIA_RPC_URL
        value: https://eth-sepolia.g.alchemy.com/v2/L6GkcIxENz-4j7Yj89Jmk
      - key: EVM_WALLET_PRIVATE_KEY
        value: 0x3af7b388fa9a08b46f583319d70d9df502cfc0ac853e2bb3ff53cefc436e5a4c
      - key: GOOGLE_SERVICE_ACCOUNT_KEY
        value: ./src/config/google-service-account.json
      - key: GOOGLE_DRIVE_FOLDER_ID
        value: 1k13g71_B-bk9K_dNmG1BjJZqZEZYEtWR
      - key: BACKUP_ENABLED
        value: true