const COINS = {
  USDT: 'USDT',
  BTC: 'BTC',
  ETH: 'ETH'
};

const NETWORKS = {
  TRC20: 'TRC20',
  BEP20: 'BEP20'
};

const ORDER_STATUS = {
  WAITING_PAYMENT: 'WAITING_PAYMENT',
  PAYMENT_UPLOADED: 'PAYMENT_UPLOADED',
  PAYMENT_VERIFIED: 'PAYMENT_VERIFIED',
  CRYPTO_SENT: 'CRYPTO_SENT',
  COMPLETED: 'COMPLETED',
  EXPIRED: 'EXPIRED',
  REJECTED: 'REJECTED'
};

const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED'
};

const ORDER_EXPIRY_MINUTES = 30;

const FEE = 500;

module.exports = {
  COINS,
  NETWORKS,
  ORDER_STATUS,
  PAYMENT_STATUS,
  ORDER_EXPIRY_MINUTES,
  FEE
};
